### ISSUE TITLE
List of string_scan.cpp bugs.

### ISSUE THREAD

**Issue by Jeffrey10th** [Jeffrey10th/simple-cpp#1]
Unfortunately, string_scan.cpp, unlike a lot other programs - comes shipped with a lot of bugs. Here are a list of currently-found bugs. This issue will be closed once all bugs are addressed. 

If you found a new bug, please [open a new issue](https://github.com/Jeffrey10th/simple-cpp/issues/new) here and I will look into it.

Issues that are currently found:

1. The **if loop** seems *very* problematic (huge bug). The code snippet seems unable to accurately scan all words.

2. Last recurring word will not be counted inside the loop.

**Comment by ghost** [comment]
I will look into it. Thanks, @Jeffrey10th for your hard work.
